/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wooruang_jnng_jni_ReqRecvSocket */

#ifndef _Included_com_wooruang_jnng_jni_ReqRecvSocket
#define _Included_com_wooruang_jnng_jni_ReqRecvSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wooruang_jnng_jni_ReqRecvSocket
 * Method:    nng_rep0_open
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_ReqRecvSocket_nng_1rep0_1open
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wooruang_jnng_jni_ReqRecvSocket
 * Method:    nng_rep0_open_raw
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_ReqRecvSocket_nng_1rep0_1open_1raw
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
