/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wooruang_jnng_jni_protocol_reqrep0_Req */

#ifndef _Included_com_wooruang_jnng_jni_protocol_reqrep0_Req
#define _Included_com_wooruang_jnng_jni_protocol_reqrep0_Req
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wooruang_jnng_jni_protocol_reqrep0_Req
 * Method:    nng_req0_open
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_protocol_reqrep0_Req_nng_1req0_1open
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_wooruang_jnng_jni_protocol_reqrep0_Req
 * Method:    nng_req0_open_raw
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_protocol_reqrep0_Req_nng_1req0_1open_1raw
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
