/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wooruang_jnng_JNNG */

#ifndef _Included_com_wooruang_jnng_JNNG
#define _Included_com_wooruang_jnng_JNNG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wooruang_jnng_JNNG
 * Method:    nng_listen
 * Signature: (JLjava/lang/String;JI)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_JNNG_nng_1listen
  (JNIEnv *, jobject, jlong, jstring, jlong, jint);

/*
 * Class:     com_wooruang_jnng_JNNG
 * Method:    nng_recv
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_JNNG_nng_1recv
  (JNIEnv *, jobject, jlong, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
