/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wooruang_jnng_jni_NNG */

#ifndef _Included_com_wooruang_jnng_jni_NNG
#define _Included_com_wooruang_jnng_jni_NNG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_listen
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;Ljava/lang/String;JI)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1listen
  (JNIEnv *, jclass, jobject, jstring, jlong, jint);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_dial
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;Ljava/lang/String;JI)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1dial
  (JNIEnv *, jclass, jobject, jstring, jlong, jint);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_send
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;[BI)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1send
  (JNIEnv *, jclass, jobject, jbyteArray, jint);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_recv
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;[B[JI)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1recv
  (JNIEnv *, jclass, jobject, jbyteArray, jlongArray, jint);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_free
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1free
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_close
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1close
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1strerror
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
