/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wooruang_jnng_jni_protocol_reqrep0_Rep */

#ifndef _Included_com_wooruang_jnng_jni_protocol_reqrep0_Rep
#define _Included_com_wooruang_jnng_jni_protocol_reqrep0_Rep
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wooruang_jnng_jni_protocol_reqrep0_Rep
 * Method:    nng_rep0_open
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_protocol_reqrep0_Rep_nng_1rep0_1open
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_wooruang_jnng_jni_protocol_reqrep0_Rep
 * Method:    nng_rep0_open_raw
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_protocol_reqrep0_Rep_nng_1rep0_1open_1raw
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
