/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wooruang_jnng_jni_NNG */

#ifndef _Included_com_wooruang_jnng_jni_NNG
#define _Included_com_wooruang_jnng_jni_NNG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_listen
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;Ljava/lang/String;JI)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1listen
  (JNIEnv *, jclass, jobject, jstring, jlong, jint);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_dial
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;Ljava/lang/String;JI)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1dial
  (JNIEnv *, jclass, jobject, jstring, jlong, jint);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_send
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;[BI)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1send
  (JNIEnv *, jclass, jobject, jbyteArray, jint);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_recv
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;[B[JI)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1recv
  (JNIEnv *, jclass, jobject, jbyteArray, jlongArray, jint);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_free
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1free
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_close
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1close
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_setopt
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;Ljava/lang/String;[BJ)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1setopt
  (JNIEnv *, jclass, jobject, jstring, jbyteArray, jlong);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_setopt_bool
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1setopt_1bool
  (JNIEnv *, jclass, jobject, jstring, jboolean);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_setopt_int
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1setopt_1int
  (JNIEnv *, jclass, jobject, jstring, jint);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_setopt_ms
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1setopt_1ms
  (JNIEnv *, jclass, jobject, jstring, jint);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_setopt_ptr
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1setopt_1ptr
  (JNIEnv *, jclass, jobject, jstring, jlong);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_setopt_size
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1setopt_1size
  (JNIEnv *, jclass, jobject, jstring, jlong);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_setopt_string
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1setopt_1string
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_setopt_unit64
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1setopt_1unit64
  (JNIEnv *, jclass, jobject, jstring, jlong);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_getopt
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;Ljava/lang/String;[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1getopt
  (JNIEnv *, jclass, jobject, jstring, jbyteArray, jlongArray);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_getopt_int
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1getopt_1int
  (JNIEnv *, jclass, jobject, jstring, jintArray);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_getopt_ms
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1getopt_1ms
  (JNIEnv *, jclass, jobject, jstring, jintArray);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_getopt_size
 * Signature: (Lcom/wooruang/jnng/jni/NNGSocket;Ljava/lang/String;[J)I
 */
JNIEXPORT jint JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1getopt_1size
  (JNIEnv *, jclass, jobject, jstring, jlongArray);

/*
 * Class:     com_wooruang_jnng_jni_NNG
 * Method:    nng_strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wooruang_jnng_jni_NNG_nng_1strerror
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
